spring:

  config:
    import: vault://
  cloud:
    vault:
      uri: http://localhost:8200
      token: ${VAULT_TOKEN:root-token}
      kv:
        enabled: true
        backend: secret

  application:
    name: participant-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/oauth

  datasource:
    url: jdbc:postgresql://localhost:5434/participant_service_db
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true


  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  management:
    endpoints:
      web:
        exposure:
          include: health,info,metrics,prometheus
    endpoint:
      health:
        show-details: always

server:
    port: 8081