apiVersion: v1
kind: Service
metadata:
  name: {{ include "keycloak.fullname" . }}
  namespace: eventreg
  labels:
    app: {{ include "keycloak.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "keycloak.fullname" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      name: http