apiVersion: v1
kind: Service
metadata:
  name: {{ include "vault.fullname" . }}
  namespace: eventreg
spec:
  type: ClusterIP
  selector:
    app: {{ include "vault.fullname" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      name: http