plugins {
    id 'java'
    id 'checkstyle'
    id 'application'
    id("com.diffplug.spotless") version "8.9.0"
}

group = 'com.eventreg'
version = '1.0-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

application {
    mainClass = 'view.Main'
}

configurations {
    checkstyleConfig
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    compileOnly 'org.projectlombok:lombok:1.18.46'
    annotationProcessor 'org.projectlombok:lombok:1.18.46'

    testCompileOnly 'org.projectlombok:lombok:1.18.46'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.46'

    checkstyleConfig("com.puppycrawl.tools:checkstyle:10.18.0") {
        transitive = false
    }
}

checkstyle {
    toolVersion = '10.18.0'
    config = resources.text.fromArchiveEntry(configurations.checkstyleConfig, 'google_checks.xml')
}

spotless {
    java {
        googleJavaFormat()
    }
}

test {
    useJUnitPlatform()
}

run {
    standardInput = System.in
}