spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eventreg_db
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true


  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true