{{- if .Values.ingress.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ingress.tlsSecretName }}
  namespace: eventreg
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get "files/tls.crt" | b64enc }}
  tls.key: {{ .Files.Get "files/tls.key" | b64enc }}
{{- end }}