spring:

  config:
    import: vault://
  cloud:
    vault:
      uri: http://localhost:8200
      token: ${VAULT_TOKEN:root-token}
      kv:
        enabled: true
        backend: secret

  application:
    name: event-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/oauth

  datasource:
    url: jdbc:postgresql://localhost:5435/event_service_db
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true


  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  management:
    endpoints:
      web:
        exposure:
          include: health,info,metrics,prometheus
    endpoint:
      health:
        show-details: always

dadata:
  client:
    token: ${dadata.token}


waiting-queue:
  scheduler:
    fixed-rate-ms: 60000
    limit: 100

resilience4j:
  circuitbreaker:
    circuitBreakerAspectOrder: 1
    instances:
      event-registration-service-circuit-breaker:
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 5s
        sliding-window-size: 10
      notification-service-circuit-breaker:
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 5s
        sliding-window-size: 10
  retry:
    retryAspectOrder: 2
    instances:
      event-registration-service-retry:
        max-attempts: 3
        wait-duration: 1s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2


server:
  port: 8082